name: Sync ngspice mirror

on:
  schedule:
    - cron: '16 18 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_REPOSITORY_OWNER }}/ngspice-mirror
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup upstream remote
        run: |
          git remote add upstream https://git.code.sf.net/p/ngspice/ngspice

      - name: Sync with mirror
        run: |
          git fetch -p upstream
          git push --mirror
